-- Update carrier_drivers homeTerminalCode and locationId from spreadsheet
-- Generated from contractor locations.xlsx

-- Update homeTerminalCode for all drivers
UPDATE carrier_drivers SET
  "homeTerminalCode" = CASE "externalDriverId"
    WHEN 'ZT02' THEN 'ABQ'
    WHEN 'BLK4' THEN 'ABQ'
    WHEN 'AB03' THEN 'ABQ'
    WHEN 'BK12' THEN 'ABQ'
    WHEN 'BK13' THEN 'ABQ'
    WHEN 'ZB01' THEN 'ABQ'
    WHEN 'ZT01' THEN 'ABQ'
    WHEN 'BLK9' THEN 'ABQ'
    WHEN 'BLK2' THEN 'ABQ'
    WHEN 'ZT04' THEN 'ABQ'
    WHEN 'RA02' THEN 'ABQ'
    WHEN 'BK16' THEN 'ABQ'
    WHEN 'HSS1' THEN 'ABQ'
    WHEN 'HSS2' THEN 'ABQ'
    WHEN 'HSS3' THEN 'ABQ'
    WHEN 'ZT05' THEN 'ABQ'
    WHEN 'ZT03' THEN 'ABQ'
    WHEN 'BK14' THEN 'ABQ'
    WHEN 'ABX1' THEN 'ABQ'
    WHEN 'BK15' THEN 'ABQ'
    WHEN 'BLK1' THEN 'ABQ'
    WHEN 'BLK6' THEN 'ABQ'
    WHEN 'RA01' THEN 'ABQ'
    WHEN 'BLK5' THEN 'ABQ'
    WHEN 'BLK0' THEN 'ABQ'
    WHEN 'BK11' THEN 'ABQ'
    WHEN 'ZT06' THEN 'ABQ'
    WHEN 'BLK8' THEN 'ABQ'
    WHEN 'BLK7' THEN 'ABQ'
    WHEN 'BIL1' THEN 'BIL'
    WHEN 'BL01' THEN 'BIL'
    WHEN 'BL02' THEN 'BIL'
    WHEN 'BL03' THEN 'BIL'
    WHEN 'BT44' THEN 'BIL'
    WHEN 'CT56' THEN 'BIL'
    WHEN 'RPR1' THEN 'BIL'
    WHEN 'GF50' THEN 'BIL'
    WHEN 'CT55' THEN 'BIL'
    WHEN 'CT57' THEN 'BIL'
    WHEN 'AP11' THEN 'BIL'
    WHEN 'APM1' THEN 'BIL'
    WHEN 'PC11' THEN 'BIL'
    WHEN 'R304' THEN 'BIL'
    WHEN 'R3X1' THEN 'BIL'
    WHEN 'R301' THEN 'BIL'
    WHEN 'PC22' THEN 'BIL'
    WHEN 'R302' THEN 'BIL'
    WHEN 'R303' THEN 'BIL'
    WHEN 'WS01' THEN 'BIL'
    WHEN 'DT33' THEN 'BIS'
    WHEN 'BI01' THEN 'BIS'
    WHEN 'BI02' THEN 'BIS'
    WHEN 'BI03' THEN 'BIS'
    WHEN 'BTLRBIS' THEN 'BIS'
    WHEN 'TIN1' THEN 'BIS'
    WHEN 'B104' THEN 'BIS'
    WHEN 'BT55' THEN 'BIS'
    WHEN 'TIN2' THEN 'BIS'
    WHEN 'BO01' THEN 'BOI'
    WHEN 'BO02' THEN 'BOI'
    WHEN 'BO03' THEN 'BOI'
    WHEN 'BT01' THEN 'BTM'
    WHEN 'BT02' THEN 'BTM'
    WHEN 'BT03' THEN 'BTM'
    WHEN 'OL91' THEN 'BTM'
    WHEN 'BY01' THEN 'BYI'
    WHEN 'BY02' THEN 'BYI'
    WHEN 'BY03' THEN 'BYI'
    WHEN 'BZ01' THEN 'BZN'
    WHEN 'BZ02' THEN 'BZN'
    WHEN 'BZ03' THEN 'BZN'
    WHEN 'CA01' THEN 'CPR'
    WHEN 'CA02' THEN 'CPR'
    WHEN 'CA03' THEN 'CPR'
    WHEN 'DCB1' THEN 'DEM'
    WHEN 'JC12' THEN 'DEM'
    WHEN 'GT42' THEN 'DEN'
    WHEN 'GT16' THEN 'DEN'
    WHEN 'GT14' THEN 'DEN'
    WHEN 'ALI1' THEN 'DEN'
    WHEN 'RED2' THEN 'DEN'
    WHEN 'EA01' THEN 'DEN'
    WHEN 'ROY0' THEN 'DEN'
    WHEN 'RB24' THEN 'DEN'
    WHEN 'RB20' THEN 'DEN'
    WHEN 'GTZ5' THEN 'DEN'
    WHEN 'COL2' THEN 'DEN'
    WHEN 'GT39' THEN 'DEN'
    WHEN 'DN01' THEN 'DEN'
    WHEN 'DN02' THEN 'DEN'
    WHEN 'DN03' THEN 'DEN'
    WHEN 'GT44' THEN 'DEN'
    WHEN 'EDK1' THEN 'DEN'
    WHEN 'OOES' THEN 'DEN'
    WHEN 'REL3' THEN 'DEN'
    WHEN 'GT22' THEN 'DEN'
    WHEN 'GTZ7' THEN 'DEN'
    WHEN 'GT41' THEN 'DEN'
    WHEN 'GTZ9' THEN 'DEN'
    WHEN 'GT33' THEN 'DEN'
    WHEN 'EA02' THEN 'DEN'
    WHEN 'EA05' THEN 'DEN'
    WHEN 'RED5' THEN 'DEN'
    WHEN 'EA10' THEN 'DEN'
    WHEN 'GT38' THEN 'DEN'
    WHEN 'EA09' THEN 'DEN'
    WHEN 'JR26' THEN 'DEN'
    WHEN 'AZK1' THEN 'DEN'
    WHEN 'ROY3' THEN 'DEN'
    WHEN 'GT12' THEN 'DEN'
    WHEN 'ROY1' THEN 'DEN'
    WHEN 'EA03' THEN 'DEN'
    WHEN 'RB22' THEN 'DEN'
    WHEN 'GT30' THEN 'DEN'
    WHEN 'HGX1' THEN 'DEN'
    WHEN 'HGX2' THEN 'DEN'
    WHEN 'HGX3' THEN 'DEN'
    WHEN 'GT40' THEN 'DEN'
    WHEN 'GT24' THEN 'DEN'
    WHEN 'GT35' THEN 'DEN'
    WHEN 'GT20' THEN 'DEN'
    WHEN 'TWT1' THEN 'DEN'
    WHEN 'JR22' THEN 'DEN'
    WHEN 'RB25' THEN 'DEN'
    WHEN 'MT11' THEN 'DEN'
    WHEN 'GT15' THEN 'DEN'
    WHEN 'RED6' THEN 'DEN'
    WHEN 'RB15' THEN 'DEN'
    WHEN 'EA12' THEN 'DEN'
    WHEN 'GTZ8' THEN 'DEN'
    WHEN 'GT31' THEN 'DEN'
    WHEN 'GT37' THEN 'DEN'
    WHEN 'RED1' THEN 'DEN'
    WHEN 'GT34' THEN 'DEN'
    WHEN 'GT48' THEN 'DEN'
    WHEN 'GT36' THEN 'DEN'
    WHEN 'NA11' THEN 'DEN'
    WHEN 'NA10' THEN 'DEN'
    WHEN 'GTZ4' THEN 'DEN'
    WHEN 'GT26' THEN 'DEN'
    WHEN 'GT21' THEN 'DEN'
    WHEN 'NA16' THEN 'DEN'
    WHEN 'GTZ2' THEN 'DEN'
    WHEN 'GT25' THEN 'DEN'
    WHEN 'EA06' THEN 'DEN'
    WHEN 'REL2' THEN 'DEN'
    WHEN 'JR25' THEN 'DEN'
    WHEN 'GT18' THEN 'DEN'
    WHEN 'PER3' THEN 'DEN'
    WHEN 'CT02' THEN 'DEN'
    WHEN 'GT19' THEN 'DEN'
    WHEN 'REL5' THEN 'DEN'
    WHEN 'RB13' THEN 'DEN'
    WHEN 'QST1' THEN 'DEN'
    WHEN 'JR23' THEN 'DEN'
    WHEN 'GT50' THEN 'DEN'
    WHEN 'GT45' THEN 'DEN'
    WHEN 'COL1' THEN 'DEN'
    WHEN 'GT10' THEN 'DEN'
    WHEN 'DEN1' THEN 'DEN'
    WHEN 'DEN2' THEN 'DEN'
    WHEN 'GTZ3' THEN 'DEN'
    WHEN 'PER1' THEN 'DEN'
    WHEN 'PER2' THEN 'DEN'
    WHEN 'PER4' THEN 'DEN'
    WHEN 'REB1' THEN 'DEN'
    WHEN 'DEN3' THEN 'DEN'
    WHEN 'QKS1' THEN 'DEN'
    WHEN 'QKS2' THEN 'DEN'
    WHEN 'GT23' THEN 'DEN'
    WHEN 'GTZ6' THEN 'DEN'
    WHEN 'GT47' THEN 'DEN'
    WHEN 'GT29' THEN 'DEN'
    WHEN 'EA04' THEN 'DEN'
    WHEN 'GT27' THEN 'DEN'
    WHEN 'RM12' THEN 'DEN'
    WHEN 'RM13' THEN 'DEN'
    WHEN 'RMF1' THEN 'DEN'
    WHEN 'RM10' THEN 'DEN'
    WHEN 'RMF2' THEN 'DEN'
    WHEN 'RMF3' THEN 'DEN'
    WHEN 'RMF4' THEN 'DEN'
    WHEN 'RMF5' THEN 'DEN'
    WHEN 'RMF6' THEN 'DEN'
    WHEN 'RMF7' THEN 'DEN'
    WHEN 'RMF8' THEN 'DEN'
    WHEN 'RB21' THEN 'DEN'
    WHEN 'EA08' THEN 'DEN'
    WHEN 'OORS' THEN 'DEN'
    WHEN 'JQ11' THEN 'DEN'
    WHEN 'GT28' THEN 'DEN'
    WHEN 'EA07' THEN 'DEN'
    WHEN 'RED3' THEN 'DEN'
    WHEN 'GMT1' THEN 'DEN'
    WHEN 'STP1' THEN 'DEN'
    WHEN 'TQL1' THEN 'DEN'
    WHEN 'TQL2' THEN 'DEN'
    WHEN 'TQL3' THEN 'DEN'
    WHEN 'TQL4' THEN 'DEN'
    WHEN 'TQL5' THEN 'DEN'
    WHEN 'TRI1' THEN 'DEN'
    WHEN 'TRI2' THEN 'DEN'
    WHEN 'GTZ1' THEN 'DEN'
    WHEN 'GTZ0' THEN 'DEN'
    WHEN 'COL3' THEN 'DEN'
    WHEN 'GT32' THEN 'DEN'
    WHEN 'SDE1' THEN 'DEN'
    WHEN 'TUT1' THEN 'DFW'
    WHEN 'DAN1' THEN 'DFW'
    WHEN 'MJW1' THEN 'DFW'
    WHEN 'ECO1' THEN 'DFW'
    WHEN 'ML29' THEN 'DFW'
    WHEN 'QS01' THEN 'DFW'
    WHEN 'QS02' THEN 'DFW'
    WHEN 'QS03' THEN 'DFW'
    WHEN 'DF01' THEN 'DFW'
    WHEN 'DF02' THEN 'DFW'
    WHEN 'DF03' THEN 'DFW'
    WHEN 'EMJ1' THEN 'DFW'
    WHEN 'ML24' THEN 'DFW'
    WHEN 'ML28' THEN 'DFW'
    WHEN 'ML27' THEN 'DFW'
    WHEN 'DEL5' THEN 'DFW'
    WHEN 'ME12' THEN 'DFW'
    WHEN 'MAX1' THEN 'DFW'
    WHEN 'BRA2' THEN 'DFW'
    WHEN 'SL55' THEN 'DFW'
    WHEN 'ME11' THEN 'DFW'
    WHEN 'BRA1' THEN 'DFW'
    WHEN 'MJW4' THEN 'DFW'
    WHEN 'MJW2' THEN 'DFW'
    WHEN 'ME13' THEN 'DFW'
    WHEN 'RAJ1' THEN 'DFW'
    WHEN 'MJW3' THEN 'DFW'
    WHEN 'KCF1' THEN 'DFW'
    WHEN 'HT33' THEN 'DFW'
    WHEN 'PLP1' THEN 'DFW'
    WHEN 'ML26' THEN 'DFW'
    WHEN 'FLA1' THEN 'DFW'
    WHEN 'ML23' THEN 'DFW'
    WHEN 'ML22' THEN 'DFW'
    WHEN 'VR11' THEN 'DFW'
    WHEN 'ML25' THEN 'DFW'
    WHEN 'SS77' THEN 'DFW'
    WHEN 'DI01' THEN 'DIK'
    WHEN 'DI02' THEN 'DIK'
    WHEN 'DI03' THEN 'DIK'
    WHEN 'DOD1' THEN 'DOD'
    WHEN 'DR01' THEN 'DRO'
    WHEN 'DR02' THEN 'DRO'
    WHEN 'DR03' THEN 'DRO'
    WHEN 'UNO1' THEN 'DRO'
    WHEN 'USR1' THEN 'DRO'
    WHEN 'ACD1' THEN 'DSM'
    WHEN 'ACD2' THEN 'DSM'
    WHEN 'BIN1' THEN 'DSM'
    WHEN 'BIN3' THEN 'DSM'
    WHEN 'SPA1' THEN 'DSM'
    WHEN 'BIN4' THEN 'DSM'
    WHEN 'AMM1' THEN 'DSM'
    WHEN 'ELG1' THEN 'DSM'
    WHEN 'DD12' THEN 'DSM'
    WHEN 'DRA1' THEN 'DSM'
    WHEN 'NA03' THEN 'DSM'
    WHEN 'KK02' THEN 'DSM'
    WHEN 'KEM1' THEN 'DSM'
    WHEN 'SAB3' THEN 'DSM'
    WHEN 'NA87' THEN 'DSM'
    WHEN 'DS01' THEN 'DSM'
    WHEN 'DS02' THEN 'DSM'
    WHEN 'DS03' THEN 'DSM'
    WHEN 'TW01' THEN 'DSM'
    WHEN 'DD11' THEN 'DSM'
    WHEN 'FRO1' THEN 'DSM'
    WHEN 'KK04' THEN 'DSM'
    WHEN 'RJ02' THEN 'DSM'
    WHEN 'FR01' THEN 'DSM'
    WHEN 'FR02' THEN 'DSM'
    WHEN 'UNT1' THEN 'DSM'
    WHEN 'SWT1' THEN 'DSM'
    WHEN 'RJ01' THEN 'DSM'
    WHEN 'LEA1' THEN 'DSM'
    WHEN 'NA86' THEN 'DSM'
    WHEN 'KK03' THEN 'DSM'
    WHEN 'TW03' THEN 'DSM'
    WHEN 'KK07' THEN 'DSM'
    WHEN 'KK01' THEN 'DSM'
    WHEN 'NA88' THEN 'DSM'
    WHEN 'TW02' THEN 'DSM'
    WHEN 'KK05' THEN 'DSM'
    WHEN 'PTL1' THEN 'DSM'
    WHEN 'BIN2' THEN 'DSM'
    WHEN 'DD13' THEN 'DSM'
    WHEN 'NA04' THEN 'DSM'
    WHEN 'OL84' THEN 'DSM'
    WHEN 'OL85' THEN 'DSM'
    WHEN 'OL99' THEN 'DSM'
    WHEN 'KK06' THEN 'DSM'
    WHEN 'PDS1' THEN 'DSM'
    WHEN 'RJ03' THEN 'DSM'
    WHEN 'RJ04' THEN 'DSM'
    WHEN 'BX01' THEN 'DSM'
    WHEN 'RJ05' THEN 'DSM'
    WHEN 'SWT3' THEN 'DSM'
    WHEN 'NA90' THEN 'DSM'
    WHEN 'VE11' THEN 'DSM'
    WHEN 'NA89' THEN 'DSM'
    WHEN 'TW04' THEN 'DSM'
    WHEN 'TW05' THEN 'DSM'
    WHEN 'NA91' THEN 'DSM'
    WHEN 'DU01' THEN 'DUL'
    WHEN 'DU02' THEN 'DUL'
    WHEN 'DU03' THEN 'DUL'
    WHEN '764Z' THEN 'ELP'
    WHEN '764Y' THEN 'ELP'
    WHEN 'JOY1' THEN 'ELP'
    WHEN '764X' THEN 'ELP'
    WHEN 'EL01' THEN 'ELP'
    WHEN 'EL02' THEN 'ELP'
    WHEN 'EL03' THEN 'ELP'
    WHEN '764G' THEN 'ELP'
    WHEN 'DJE1' THEN 'ELP'
    WHEN '764N' THEN 'ELP'
    WHEN '764H' THEN 'ELP'
    WHEN '764K' THEN 'ELP'
    WHEN 'JFT1' THEN 'ELP'
    WHEN '764C' THEN 'ELP'
    WHEN '764J' THEN 'ELP'
    WHEN 'GNS1' THEN 'ELP'
    WHEN 'TP01' THEN 'ELP'
    WHEN '764F' THEN 'ELP'
    WHEN '764M' THEN 'ELP'
    WHEN 'S601' THEN 'ELP'
    WHEN 'NAI1' THEN 'ELP'
    WHEN 'TRW4' THEN 'FAR'
    WHEN 'BTLRFAR' THEN 'FAR'
    WHEN 'BTLRJMS' THEN 'FAR'
    WHEN 'FA01' THEN 'FAR'
    WHEN 'FA02' THEN 'FAR'
    WHEN 'FA03' THEN 'FAR'
    WHEN 'TRW3' THEN 'FAR'
    WHEN 'TRW1' THEN 'FAR'
    WHEN 'SCF1' THEN 'FAR'
    WHEN 'MAN1' THEN 'FAR'
    WHEN 'MAN2' THEN 'FAR'
    WHEN 'MAN3' THEN 'FAR'
    WHEN 'TRW2' THEN 'FAR'
    WHEN 'NA65' THEN 'FAR'
    WHEN 'OL05' THEN 'FAR'
    WHEN 'OL12' THEN 'FAR'
    WHEN 'OL13' THEN 'FAR'
    WHEN 'OL14' THEN 'FAR'
    WHEN 'OL16' THEN 'FAR'
    WHEN 'OL17' THEN 'FAR'
    WHEN 'OL19' THEN 'FAR'
    WHEN 'OL22' THEN 'FAR'
    WHEN 'OL25' THEN 'FAR'
    WHEN 'OL30' THEN 'FAR'
    WHEN 'OL31' THEN 'FAR'
    WHEN 'OL35' THEN 'FAR'
    WHEN 'OL36' THEN 'FAR'
    WHEN 'OL37' THEN 'FAR'
    WHEN 'OL38' THEN 'FAR'
    WHEN 'OL44' THEN 'FAR'
    WHEN 'OL46' THEN 'FAR'
    WHEN 'OL51' THEN 'FAR'
    WHEN 'OL63' THEN 'FAR'
    WHEN 'OL64' THEN 'FAR'
    WHEN 'OL65' THEN 'FAR'
    WHEN 'OL68' THEN 'FAR'
    WHEN 'OL69' THEN 'FAR'
    WHEN 'OL71' THEN 'FAR'
    WHEN 'OL76' THEN 'FAR'
    WHEN 'OL77' THEN 'FAR'
    WHEN 'OL79' THEN 'FAR'
    WHEN 'OL80' THEN 'FAR'
    WHEN 'OL81' THEN 'FAR'
    WHEN 'OL82' THEN 'FAR'
    WHEN 'OL83' THEN 'FAR'
    WHEN 'OL88' THEN 'FAR'
    WHEN 'OL89' THEN 'FAR'
    WHEN 'OL90' THEN 'FAR'
    WHEN 'OL92' THEN 'FAR'
    WHEN 'OL93' THEN 'FAR'
    WHEN 'OL94' THEN 'FAR'
    WHEN 'OL95' THEN 'FAR'
    WHEN 'OL96' THEN 'FAR'
    WHEN 'OL97' THEN 'FAR'
    WHEN 'OL98' THEN 'FAR'
    WHEN 'OLX1' THEN 'FAR'
    WHEN 'OL01' THEN 'FAR'
    WHEN 'OL10' THEN 'FAR'
    WHEN 'OL11' THEN 'FAR'
    WHEN 'OL15' THEN 'FAR'
    WHEN 'OL02' THEN 'FAR'
    WHEN 'OL20' THEN 'FAR'
    WHEN 'OL21' THEN 'FAR'
    WHEN 'OL23' THEN 'FAR'
    WHEN 'OL24' THEN 'FAR'
    WHEN 'OL26' THEN 'FAR'
    WHEN 'OL27' THEN 'FAR'
    WHEN 'OL28' THEN 'FAR'
    WHEN 'OL29' THEN 'FAR'
    WHEN 'OL03' THEN 'FAR'
    WHEN 'OL32' THEN 'FAR'
    WHEN 'OL33' THEN 'FAR'
    WHEN 'OL34' THEN 'FAR'
    WHEN 'OL04' THEN 'FAR'
    WHEN 'OL06' THEN 'FAR'
    WHEN 'OL66' THEN 'FAR'
    WHEN 'OL07' THEN 'FAR'
    WHEN 'OL08' THEN 'FAR'
    WHEN 'OL09' THEN 'FAR'
    WHEN 'OLT1' THEN 'FAR'
    WHEN 'OWS1' THEN 'FAR'
    WHEN 'AW11' THEN 'FAR'
    WHEN 'NRE1' THEN 'FAR'
    WHEN 'HH24' THEN 'FAR'
    WHEN 'SCF2' THEN 'FAR'
    WHEN 'FO01' THEN 'FON'
    WHEN 'FO02' THEN 'FON'
    WHEN 'FO03' THEN 'FON'
    WHEN 'GA01' THEN 'GAR'
    WHEN 'GA02' THEN 'GAR'
    WHEN 'GA03' THEN 'GAR'
    WHEN 'GF01' THEN 'GFK'
    WHEN 'GF02' THEN 'GFK'
    WHEN 'GF03' THEN 'GFK'
    WHEN 'GJ01' THEN 'GJT'
    WHEN 'GJ02' THEN 'GJT'
    WHEN 'GJ03' THEN 'GJT'
    WHEN 'SPL1' THEN 'GJT'
    WHEN 'GI01' THEN 'GRI'
    WHEN 'GI02' THEN 'GRI'
    WHEN 'GI03' THEN 'GRI'
    WHEN 'JEC1' THEN 'GRI'
    WHEN 'GT01' THEN 'GTF'
    WHEN 'GT02' THEN 'GTF'
    WHEN 'GT03' THEN 'GTF'
    WHEN 'LH01' THEN 'GTF'
    WHEN 'HY01' THEN 'HAY'
    WHEN 'HY02' THEN 'HAY'
    WHEN 'HY03' THEN 'HAY'
    WHEN 'HAY1' THEN 'HAY'
    WHEN 'ST88' THEN 'HOU'
    WHEN 'HH25' THEN 'HOU'
    WHEN 'GF55' THEN 'HOU'
    WHEN 'ST77' THEN 'HOU'
    WHEN 'AKA2' THEN 'HOU'
    WHEN 'HO02' THEN 'HOU'
    WHEN 'HO03' THEN 'HOU'
    WHEN 'ST44' THEN 'HOU'
    WHEN 'ST99' THEN 'HOU'
    WHEN 'LT11' THEN 'HOU'
    WHEN 'ZT12' THEN 'HOU'
    WHEN 'ST75' THEN 'HOU'
    WHEN 'ST55' THEN 'HOU'
    WHEN 'ID01' THEN 'IDA'
    WHEN 'ID02' THEN 'IDA'
    WHEN 'ID03' THEN 'IDA'
    WHEN 'IOL1' THEN 'IOL'
    WHEN '247E' THEN 'KCY'
    WHEN 'RNA1' THEN 'KCY'
    WHEN 'RE55' THEN 'KCY'
    WHEN 'USC4' THEN 'KCY'
    WHEN 'GE44' THEN 'KCY'
    WHEN 'SET2' THEN 'KCY'
    WHEN 'HH23' THEN 'KCY'
    WHEN 'JR04' THEN 'KCY'
    WHEN 'SS05' THEN 'KCY'
    WHEN 'SS12' THEN 'KCY'
    WHEN 'ARM1' THEN 'KCY'
    WHEN 'ARM2' THEN 'KCY'
    WHEN 'ARM3' THEN 'KCY'
    WHEN 'NA76' THEN 'KCY'
    WHEN 'KEE1' THEN 'KCY'
    WHEN 'JLL1' THEN 'KCY'
    WHEN 'DE15' THEN 'KCY'
    WHEN 'JAS1' THEN 'KCY'
    WHEN 'KE11' THEN 'KCY'
    WHEN 'QUI3' THEN 'KCY'
    WHEN 'TUT2' THEN 'KCY'
    WHEN 'ST66' THEN 'KCY'
    WHEN 'KEE6' THEN 'KCY'
    WHEN 'SAM1' THEN 'KCY'
    WHEN 'JRS1' THEN 'KCY'
    WHEN 'SS16' THEN 'KCY'
    WHEN 'SS04' THEN 'KCY'
    WHEN 'PROC' THEN 'KCY'
    WHEN 'VR22' THEN 'KCY'
    WHEN 'PROK' THEN 'KCY'
    WHEN 'FA11' THEN 'KCY'
    WHEN 'DKT1' THEN 'KCY'
    WHEN 'RR11' THEN 'KCY'
    WHEN 'SS14' THEN 'KCY'
    WHEN 'DE34' THEN 'KCY'
    WHEN 'BLE1' THEN 'KCY'
    WHEN 'DEL2' THEN 'KCY'
    WHEN 'HET2' THEN 'KCY'
    WHEN 'PR45' THEN 'KCY'
    WHEN 'CR11' THEN 'KCY'
    WHEN 'SS02' THEN 'KCY'
    WHEN 'TRL2' THEN 'KCY'
    WHEN 'HA11' THEN 'KCY'
    WHEN 'KEE7' THEN 'KCY'
    WHEN 'PHA1' THEN 'KCY'
    WHEN 'NAX7' THEN 'KCY'
    WHEN 'GBT1' THEN 'KCY'
    WHEN 'LTN1' THEN 'KCY'
    WHEN 'DE55' THEN 'KCY'
    WHEN 'ASK1' THEN 'KCY'
    WHEN 'ST22' THEN 'KCY'
    WHEN 'QUI1' THEN 'KCY'
    WHEN 'DAH1' THEN 'KCY'
    WHEN 'VKT1' THEN 'KCY'
    WHEN 'KAG1' THEN 'KCY'
    WHEN 'SS15' THEN 'KCY'
    WHEN 'JR01' THEN 'KCY'
    WHEN 'SS06' THEN 'KCY'
    WHEN 'BHP2' THEN 'KCY'
    WHEN 'SS17' THEN 'KCY'
    WHEN 'JR06' THEN 'KCY'
    WHEN 'SS10' THEN 'KCY'
    WHEN 'TRKN' THEN 'KCY'
    WHEN 'JR02' THEN 'KCY'
    WHEN 'DEL9' THEN 'KCY'
    WHEN 'KC01' THEN 'KCY'
    WHEN 'KC02' THEN 'KCY'
    WHEN 'KC03' THEN 'KCY'
    WHEN 'TRJN' THEN 'KCY'
    WHEN 'QUI4' THEN 'KCY'
    WHEN 'UNI1' THEN 'KCY'
    WHEN 'TRLY' THEN 'KCY'
    WHEN 'AJ01' THEN 'KCY'
    WHEN 'TRL3' THEN 'KCY'
    WHEN 'PROT' THEN 'KCY'
    WHEN 'TR1L' THEN 'KCY'
    WHEN 'JR03' THEN 'KCY'
    WHEN 'AJ02' THEN 'KCY'
    WHEN 'HH11' THEN 'KCY'
    WHEN 'SS07' THEN 'KCY'
    WHEN 'EA11' THEN 'KCY'
    WHEN 'KL11' THEN 'KCY'
    WHEN 'DEL7' THEN 'KCY'
    WHEN 'SS11' THEN 'KCY'
    WHEN 'MIK1' THEN 'KCY'
    WHEN 'KEE4' THEN 'KCY'
    WHEN 'QUI5' THEN 'KCY'
    WHEN 'MEC1' THEN 'KCY'
    WHEN 'KEE3' THEN 'KCY'
    WHEN 'SEE1' THEN 'KCY'
    WHEN 'NWE1' THEN 'KCY'
    WHEN 'ATZ1' THEN 'KCY'
    WHEN '3BM1' THEN 'KCY'
    WHEN 'NEL1' THEN 'KCY'
    WHEN 'SS09' THEN 'KCY'
    WHEN 'EG11' THEN 'KCY'
    WHEN 'SET3' THEN 'KCY'
    WHEN 'DC11' THEN 'KCY'
    WHEN 'AAM1' THEN 'KCY'
    WHEN 'LKR1' THEN 'KCY'
    WHEN 'SS01' THEN 'KCY'
    WHEN 'PAW1' THEN 'KCY'
    WHEN 'TRRY' THEN 'KCY'
    WHEN 'QKSL' THEN 'KCY'
    WHEN 'HH27' THEN 'KCY'
    WHEN 'HET1' THEN 'KCY'
    WHEN 'RW11' THEN 'KCY'
    WHEN 'KE55' THEN 'KCY'
    WHEN 'UT12' THEN 'KCY'
    WHEN 'QUI2' THEN 'KCY'
    WHEN 'PAM1' THEN 'KCY'
    WHEN 'TJ11' THEN 'KCY'
    WHEN 'QU02' THEN 'KCY'
    WHEN 'LEA2' THEN 'KCY'
    WHEN 'CPT1' THEN 'KCY'
    WHEN 'SS08' THEN 'KCY'
    WHEN 'NA49' THEN 'KCY'
    WHEN 'BAR1' THEN 'KCY'
    WHEN 'JR05' THEN 'KCY'
    WHEN 'TR2L' THEN 'KCY'
    WHEN 'USL1' THEN 'KCY'
    WHEN 'KEE8' THEN 'KCY'
    WHEN 'SPR1' THEN 'KCY'
    WHEN 'GL11' THEN 'KCY'
    WHEN 'SHE1' THEN 'KCY'
    WHEN 'AZW1' THEN 'KCY'
    WHEN 'UG11' THEN 'KCY'
    WHEN 'BRG1' THEN 'KCY'
    WHEN 'KS01' THEN 'KSP'
    WHEN 'KS02' THEN 'KSP'
    WHEN 'KS03' THEN 'KSP'
    WHEN 'RM11' THEN 'LAS'
    WHEN 'FS20' THEN 'LAS'
    WHEN 'GE01' THEN 'LAS'
    WHEN 'ARP1' THEN 'LAS'
    WHEN 'SP11' THEN 'LAS'
    WHEN 'GD15' THEN 'LAS'
    WHEN 'AL11' THEN 'LAS'
    WHEN 'MF11' THEN 'LAS'
    WHEN 'BST1' THEN 'LAS'
    WHEN 'BST2' THEN 'LAS'
    WHEN 'BST3' THEN 'LAS'
    WHEN 'TRA1' THEN 'LAS'
    WHEN 'CE11' THEN 'LAS'
    WHEN 'FS15' THEN 'LAS'
    WHEN 'GS25' THEN 'LAS'
    WHEN 'LTD1' THEN 'LAS'
    WHEN 'GS20' THEN 'LAS'
    WHEN 'DGT1' THEN 'LAS'
    WHEN 'GS11' THEN 'LAS'
    WHEN 'FS22' THEN 'LAS'
    WHEN 'EG55' THEN 'LAS'
    WHEN 'FIN1' THEN 'LAS'
    WHEN 'BER1' THEN 'LAS'
    WHEN 'ME22' THEN 'LAS'
    WHEN 'LK02' THEN 'LAS'
    WHEN 'AP22' THEN 'LAS'
    WHEN 'BER2' THEN 'LAS'
    WHEN 'EW11' THEN 'LAS'
    WHEN 'CH11' THEN 'LAS'
    WHEN 'OGR1' THEN 'LAS'
    WHEN 'GS14' THEN 'LAS'
    WHEN 'GS22' THEN 'LAS'
    WHEN 'INL1' THEN 'LAS'
    WHEN 'GS21' THEN 'LAS'
    WHEN 'FS21' THEN 'LAS'
    WHEN 'FS24' THEN 'LAS'
    WHEN 'AT88' THEN 'LAS'
    WHEN 'GS30' THEN 'LAS'
    WHEN 'FS13' THEN 'LAS'
    WHEN 'RE11' THEN 'LAS'
    WHEN 'GRV1' THEN 'LAS'
    WHEN 'GD17' THEN 'LAS'
    WHEN 'LL10' THEN 'LAS'
    WHEN 'LT55' THEN 'LAS'
    WHEN 'DRT9' THEN 'LAS'
    WHEN 'HGH1' THEN 'LAS'
    WHEN 'LL11' THEN 'LAS'
    WHEN 'LA01' THEN 'LAS'
    WHEN 'LA02' THEN 'LAS'
    WHEN 'LA03' THEN 'LAS'
    WHEN 'GS15' THEN 'LAS'
    WHEN 'CAP1' THEN 'LAS'
    WHEN 'FS18' THEN 'LAS'
    WHEN 'GS29' THEN 'LAS'
    WHEN 'GS19' THEN 'LAS'
    WHEN 'HKT1' THEN 'LAS'
    WHEN 'LK01' THEN 'LAS'
    WHEN 'JAC1' THEN 'LAS'
    WHEN 'TH02' THEN 'LAS'
    WHEN 'FT33' THEN 'LAS'
    WHEN 'NE55' THEN 'LAS'
    WHEN 'TH03' THEN 'LAS'
    WHEN 'GS27' THEN 'LAS'
    WHEN 'GS28' THEN 'LAS'
    WHEN 'GD12' THEN 'LAS'
    WHEN 'GS23' THEN 'LAS'
    WHEN 'AB11' THEN 'LAS'
    WHEN 'GS12' THEN 'LAS'
    WHEN 'TH01' THEN 'LAS'
    WHEN 'GD13' THEN 'LAS'
    WHEN 'ARI2' THEN 'LAS'
    WHEN 'ARI1' THEN 'LAS'
    WHEN 'AEO1' THEN 'LAS'
    WHEN 'GD16' THEN 'LAS'
    WHEN 'SP12' THEN 'LAS'
    WHEN 'BER3' THEN 'LAS'
    WHEN 'AZA1' THEN 'LAS'
    WHEN 'GS13' THEN 'LAS'
    WHEN 'FS14' THEN 'LAS'
    WHEN 'GS24' THEN 'LAS'
    WHEN 'GS16' THEN 'LAS'
    WHEN 'FS12' THEN 'LAS'
    WHEN 'GD11' THEN 'LAS'
    WHEN 'GD14' THEN 'LAS'
    WHEN 'FS11' THEN 'LAS'
    WHEN 'FS23' THEN 'LAS'
    WHEN 'GS17' THEN 'LAS'
    WHEN 'FOR1' THEN 'LAS'
    WHEN 'JG11' THEN 'LAX'
    WHEN 'LB01' THEN 'LBB'
    WHEN 'LB02' THEN 'LBB'
    WHEN 'LB03' THEN 'LBB'
    WHEN 'WRT1' THEN 'MOT'
    WHEN 'TF55' THEN 'MOT'
    WHEN 'BTLRMOT' THEN 'MOT'
    WHEN 'TF11' THEN 'MOT'
    WHEN 'SS55' THEN 'MOT'
    WHEN 'TF22' THEN 'MOT'
    WHEN 'JRY1' THEN 'MOT'
    WHEN 'TF33' THEN 'MOT'
    WHEN 'MO01' THEN 'MOT'
    WHEN 'MO02' THEN 'MOT'
    WHEN 'MO03' THEN 'MOT'
    WHEN 'TF44' THEN 'MOT'
    WHEN 'BOO2' THEN 'MSO'
    WHEN 'MI01' THEN 'MSO'
    WHEN 'MI02' THEN 'MSO'
    WHEN 'MI03' THEN 'MSO'
    WHEN 'BOO1' THEN 'MSO'
    WHEN 'TCF7' THEN 'MSP'
    WHEN 'GE22' THEN 'MSP'
    WHEN 'SK02' THEN 'MSP'
    WHEN 'RL13' THEN 'MSP'
    WHEN 'HH26' THEN 'MSP'
    WHEN 'EXP1' THEN 'MSP'
    WHEN 'WAL1' THEN 'MSP'
    WHEN 'SE22' THEN 'MSP'
    WHEN 'TC11' THEN 'MSP'
    WHEN 'RC01' THEN 'MSP'
    WHEN 'EYL1' THEN 'MSP'
    WHEN 'TCF3' THEN 'MSP'
    WHEN 'TCF6' THEN 'MSP'
    WHEN 'BU11' THEN 'MSP'
    WHEN 'PL33' THEN 'MSP'
    WHEN 'LE11' THEN 'MSP'
    WHEN 'DE11' THEN 'MSP'
    WHEN 'TT01' THEN 'MSP'
    WHEN 'DE10' THEN 'MSP'
    WHEN 'HAT1' THEN 'MSP'
    WHEN 'FRL1' THEN 'MSP'
    WHEN 'FFS1' THEN 'MSP'
    WHEN 'MVP6' THEN 'MSP'
    WHEN 'ELT1' THEN 'MSP'
    WHEN 'RL12' THEN 'MSP'
    WHEN 'TCF9' THEN 'MSP'
    WHEN 'RL11' THEN 'MSP'
    WHEN 'OZB1' THEN 'MSP'
    WHEN 'NA35' THEN 'MSP'
    WHEN 'NA02' THEN 'MSP'
    WHEN 'OL74' THEN 'MSP'
    WHEN 'SK01' THEN 'MSP'
    WHEN 'CCP1' THEN 'MSP'
    WHEN 'LOT1' THEN 'MSP'
    WHEN 'LOT2' THEN 'MSP'
    WHEN 'MVP3' THEN 'MSP'
    WHEN 'AVC1' THEN 'MSP'
    WHEN 'FL11' THEN 'MSP'
    WHEN 'OL75' THEN 'MSP'
    WHEN 'SAT1' THEN 'MSP'
    WHEN 'MON1' THEN 'MSP'
    WHEN 'MON2' THEN 'MSP'
    WHEN 'MON3' THEN 'MSP'
    WHEN 'TCF2' THEN 'MSP'
    WHEN 'WWH1' THEN 'MSP'
    WHEN 'OL18' THEN 'MSP'
    WHEN 'OL39' THEN 'MSP'
    WHEN 'OL45' THEN 'MSP'
    WHEN 'OL70' THEN 'MSP'
    WHEN 'OL72' THEN 'MSP'
    WHEN 'OL73' THEN 'MSP'
    WHEN 'OL86' THEN 'MSP'
    WHEN 'OL87' THEN 'MSP'
    WHEN 'OLM2' THEN 'MSP'
    WHEN 'OLM1' THEN 'MSP'
    WHEN 'OLM3' THEN 'MSP'
    WHEN 'OLM4' THEN 'MSP'
    WHEN 'OLM5' THEN 'MSP'
    WHEN 'OLM6' THEN 'MSP'
    WHEN 'OLM9' THEN 'MSP'
    WHEN 'OL40' THEN 'MSP'
    WHEN 'OL42' THEN 'MSP'
    WHEN 'TCF5' THEN 'MSP'
    WHEN 'RUN1' THEN 'MSP'
    WHEN 'PCE1' THEN 'MSP'
    WHEN 'PRO1' THEN 'MSP'
    WHEN 'PRO2' THEN 'MSP'
    WHEN 'PRO3' THEN 'MSP'
    WHEN 'PRO4' THEN 'MSP'
    WHEN 'PRO5' THEN 'MSP'
    WHEN 'PRO6' THEN 'MSP'
    WHEN 'PRO7' THEN 'MSP'
    WHEN 'PRO8' THEN 'MSP'
    WHEN 'PRO9' THEN 'MSP'
    WHEN 'DEL1' THEN 'MSP'
    WHEN 'DE12' THEN 'MSP'
    WHEN 'RCG1' THEN 'MSP'
    WHEN 'FT22' THEN 'MSP'
    WHEN 'CLE1' THEN 'MSP'
    WHEN 'TCF1' THEN 'MSP'
    WHEN 'MVP2' THEN 'MSP'
    WHEN 'TOT1' THEN 'MSP'
    WHEN 'TOT0' THEN 'MSP'
    WHEN 'TOT2' THEN 'MSP'
    WHEN 'TOT3' THEN 'MSP'
    WHEN 'TOT4' THEN 'MSP'
    WHEN 'TOT5' THEN 'MSP'
    WHEN 'TOT6' THEN 'MSP'
    WHEN 'TOT7' THEN 'MSP'
    WHEN 'TOT8' THEN 'MSP'
    WHEN 'TOT9' THEN 'MSP'
    WHEN 'DE13' THEN 'MSP'
    WHEN 'TTS1' THEN 'MSP'
    WHEN 'TCS1' THEN 'MSP'
    WHEN 'TCS0' THEN 'MSP'
    WHEN 'TCS2' THEN 'MSP'
    WHEN 'TCS3' THEN 'MSP'
    WHEN 'TCS4' THEN 'MSP'
    WHEN 'TCS5' THEN 'MSP'
    WHEN 'TCS6' THEN 'MSP'
    WHEN 'TCS7' THEN 'MSP'
    WHEN 'TCS8' THEN 'MSP'
    WHEN 'TCS9' THEN 'MSP'
    WHEN 'ACT3' THEN 'MSP'
    WHEN 'TCF4' THEN 'MSP'
    WHEN 'TCF8' THEN 'MSP'
    WHEN 'NC01' THEN 'NCS'
    WHEN 'NC02' THEN 'NCS'
    WHEN 'NC03' THEN 'NCS'
    WHEN 'CT01' THEN 'NCS'
    WHEN 'NA22' THEN 'NPL'
    WHEN 'WAY1' THEN 'NPL'
    WHEN 'NP01' THEN 'NPL'
    WHEN 'NP02' THEN 'NPL'
    WHEN 'NP03' THEN 'NPL'
    WHEN 'MOO4' THEN 'OMA'
    WHEN 'TUT3' THEN 'OMA'
    WHEN 'MOO1' THEN 'OMA'
    WHEN 'ATT1' THEN 'OMA'
    WHEN 'MO17' THEN 'OMA'
    WHEN 'CST1' THEN 'OMA'
    WHEN 'MO11' THEN 'OMA'
    WHEN 'IBR1' THEN 'OMA'
    WHEN 'NA60' THEN 'OMA'
    WHEN 'MOO6' THEN 'OMA'
    WHEN 'HIL2' THEN 'OMA'
    WHEN 'HIL1' THEN 'OMA'
    WHEN 'HIL3' THEN 'OMA'
    WHEN 'SLA3' THEN 'OMA'
    WHEN 'MO12' THEN 'OMA'
    WHEN 'OT12' THEN 'OMA'
    WHEN 'MO16' THEN 'OMA'
    WHEN 'SLA4' THEN 'OMA'
    WHEN 'SLA2' THEN 'OMA'
    WHEN 'JJT3' THEN 'OMA'
    WHEN 'JJT2' THEN 'OMA'
    WHEN 'JJT1' THEN 'OMA'
    WHEN 'MOO7' THEN 'OMA'
    WHEN 'NA64' THEN 'OMA'
    WHEN 'KRA1' THEN 'OMA'
    WHEN 'MOO2' THEN 'OMA'
    WHEN 'OT14' THEN 'OMA'
    WHEN 'STL1' THEN 'OMA'
    WHEN 'MOO9' THEN 'OMA'
    WHEN 'SILD' THEN 'OMA'
    WHEN 'JN01' THEN 'OMA'
    WHEN 'OO01' THEN 'OMA'
    WHEN 'OO02' THEN 'OMA'
    WHEN 'OM01' THEN 'OMA'
    WHEN 'OM02' THEN 'OMA'
    WHEN 'OM03' THEN 'OMA'
    WHEN 'MO15' THEN 'OMA'
    WHEN 'PRD1' THEN 'OMA'
    WHEN 'PRD2' THEN 'OMA'
    WHEN 'PRD3' THEN 'OMA'
    WHEN 'NTS1' THEN 'OMA'
    WHEN 'NA05' THEN 'OMA'
    WHEN 'MOO5' THEN 'OMA'
    WHEN 'MOO3' THEN 'OMA'
    WHEN 'OT15' THEN 'OMA'
    WHEN 'MO13' THEN 'OMA'
    WHEN 'OT11' THEN 'OMA'
    WHEN 'LAS1' THEN 'OMA'
    WHEN 'TLC1' THEN 'OMA'
    WHEN 'SNL1' THEN 'OMA'
    WHEN 'OT16' THEN 'OMA'
    WHEN 'MOO8' THEN 'OMA'
    WHEN 'OT13' THEN 'OMA'
    WHEN 'TRL1' THEN 'OMA'
    WHEN 'SLA1' THEN 'OMA'
    WHEN 'BM11' THEN 'OMA'
    WHEN 'WTT1' THEN 'OMA'
    WHEN 'FAL2' THEN 'OMA'
    WHEN 'ON03' THEN 'ONT'
    WHEN '3K03' THEN 'PHX'
    WHEN 'PFH5' THEN 'PHX'
    WHEN 'PF14' THEN 'PHX'
    WHEN 'BS01' THEN 'PHX'
    WHEN 'BS02' THEN 'PHX'
    WHEN 'BS03' THEN 'PHX'
    WHEN 'PFH4' THEN 'PHX'
    WHEN 'STH1' THEN 'PHX'
    WHEN 'PFH2' THEN 'PHX'
    WHEN 'RW01' THEN 'PHX'
    WHEN 'DD01' THEN 'PHX'
    WHEN 'EMM1' THEN 'PHX'
    WHEN 'PFH9' THEN 'PHX'
    WHEN 'AZD1' THEN 'PHX'
    WHEN 'PF12' THEN 'PHX'
    WHEN 'JET1' THEN 'PHX'
    WHEN '3K05' THEN 'PHX'
    WHEN '3K01' THEN 'PHX'
    WHEN 'EMM2' THEN 'PHX'
    WHEN 'TGT1' THEN 'PHX'
    WHEN '3K04' THEN 'PHX'
    WHEN 'PFH7' THEN 'PHX'
    WHEN 'JET3' THEN 'PHX'
    WHEN 'ARA1' THEN 'PHX'
    WHEN 'JET2' THEN 'PHX'
    WHEN 'UP01' THEN 'PHX'
    WHEN 'PFH3' THEN 'PHX'
    WHEN 'PFH6' THEN 'PHX'
    WHEN 'PF11' THEN 'PHX'
    WHEN 'RTR1' THEN 'PHX'
    WHEN 'USC1' THEN 'PHX'
    WHEN 'SCT1' THEN 'PHX'
    WHEN 'ONE7' THEN 'PHX'
    WHEN 'EMM3' THEN 'PHX'
    WHEN 'PFH1' THEN 'PHX'
    WHEN 'DDP1' THEN 'PHX'
    WHEN 'PH01' THEN 'PHX'
    WHEN 'PH02' THEN 'PHX'
    WHEN 'PH03' THEN 'PHX'
    WHEN 'PH04' THEN 'PHX'
    WHEN 'PH05' THEN 'PHX'
    WHEN 'PH06' THEN 'PHX'
    WHEN 'PH07' THEN 'PHX'
    WHEN 'PH08' THEN 'PHX'
    WHEN 'PH09' THEN 'PHX'
    WHEN 'PH10' THEN 'PHX'
    WHEN 'PH11' THEN 'PHX'
    WHEN 'PH12' THEN 'PHX'
    WHEN 'PH13' THEN 'PHX'
    WHEN 'PH14' THEN 'PHX'
    WHEN 'PH15' THEN 'PHX'
    WHEN '3K02' THEN 'PHX'
    WHEN 'ONE1' THEN 'PHX'
    WHEN 'ONE4' THEN 'PHX'
    WHEN 'ONE3' THEN 'PHX'
    WHEN 'ONE2' THEN 'PHX'
    WHEN 'ONE5' THEN 'PHX'
    WHEN 'SWT2' THEN 'PHX'
    WHEN 'ONE6' THEN 'PHX'
    WHEN 'PI01' THEN 'PIE'
    WHEN 'PI02' THEN 'PIE'
    WHEN 'PI03' THEN 'PIE'
    WHEN 'GTP3' THEN 'PUB'
    WHEN 'GTP4' THEN 'PUB'
    WHEN 'GTP1' THEN 'PUB'
    WHEN 'GTP5' THEN 'PUB'
    WHEN 'GTP2' THEN 'PUB'
    WHEN 'PER5' THEN 'PUB'
    WHEN 'PER6' THEN 'PUB'
    WHEN 'PU01' THEN 'PUB'
    WHEN 'PU02' THEN 'PUB'
    WHEN 'PU03' THEN 'PUB'
    WHEN 'ZA11' THEN 'RNO'
    WHEN 'CB11' THEN 'RNO'
    WHEN 'HB11' THEN 'RNO'
    WHEN 'KNN2' THEN 'RNO'
    WHEN 'TA11' THEN 'RNO'
    WHEN 'ABR1' THEN 'RNO'
    WHEN 'GTI2' THEN 'RNO'
    WHEN 'USK1' THEN 'RNO'
    WHEN 'USK2' THEN 'RNO'
    WHEN 'BC22' THEN 'RNO'
    WHEN 'LED8' THEN 'RNO'
    WHEN 'TCE2' THEN 'RNO'
    WHEN 'DTG2' THEN 'RNO'
    WHEN 'TCC1' THEN 'RNO'
    WHEN 'EE11' THEN 'RNO'
    WHEN 'SKY3' THEN 'RNO'
    WHEN 'RF01' THEN 'RNO'
    WHEN 'SE11' THEN 'RNO'
    WHEN 'RL22' THEN 'RNO'
    WHEN 'BSG1' THEN 'RNO'
    WHEN 'BHF1' THEN 'RNO'
    WHEN 'KTL1' THEN 'RNO'
    WHEN 'GO12' THEN 'RNO'
    WHEN 'GO11' THEN 'RNO'
    WHEN 'TU11' THEN 'RNO'
    WHEN 'TT12' THEN 'RNO'
    WHEN 'ST33' THEN 'RNO'
    WHEN 'JT15' THEN 'RNO'
    WHEN 'JT12' THEN 'RNO'
    WHEN 'DT44' THEN 'RNO'
    WHEN 'AT55' THEN 'RNO'
    WHEN 'GF13' THEN 'RNO'
    WHEN 'BP11' THEN 'RNO'
    WHEN 'BST4' THEN 'RNO'
    WHEN 'BST5' THEN 'RNO'
    WHEN 'BST6' THEN 'RNO'
    WHEN 'BC11' THEN 'RNO'
    WHEN 'TEM2' THEN 'RNO'
    WHEN 'GEN5' THEN 'RNO'
    WHEN 'TLF1' THEN 'RNO'
    WHEN 'KG22' THEN 'RNO'
    WHEN 'GE20' THEN 'RNO'
    WHEN 'TCE3' THEN 'RNO'
    WHEN 'LE22' THEN 'RNO'
    WHEN 'DBN1' THEN 'RNO'
    WHEN 'BMT1' THEN 'RNO'
    WHEN 'GFM1' THEN 'RNO'
    WHEN 'MDS1' THEN 'RNO'
    WHEN 'BT11' THEN 'RNO'
    WHEN 'GE11' THEN 'RNO'
    WHEN 'NL22' THEN 'RNO'
    WHEN 'ALP1' THEN 'RNO'
    WHEN 'VL11' THEN 'RNO'
    WHEN 'ELD1' THEN 'RNO'
    WHEN 'PE11' THEN 'RNO'
    WHEN 'WT44' THEN 'RNO'
    WHEN 'AK12' THEN 'RNO'
    WHEN 'DU13' THEN 'RNO'
    WHEN 'LED3' THEN 'RNO'
    WHEN 'KC11' THEN 'RNO'
    WHEN 'GST3' THEN 'RNO'
    WHEN 'LE25' THEN 'RNO'
    WHEN 'DTG3' THEN 'RNO'
    WHEN 'LED4' THEN 'RNO'
    WHEN 'RL25' THEN 'RNO'
    WHEN 'NT55' THEN 'RNO'
    WHEN 'JNM1' THEN 'RNO'
    WHEN 'MA55' THEN 'RNO'
    WHEN 'AQ11' THEN 'RNO'
    WHEN 'BL12' THEN 'RNO'
    WHEN 'MGT1' THEN 'RNO'
    WHEN 'KL55' THEN 'RNO'
    WHEN 'GEN2' THEN 'RNO'
    WHEN 'RL24' THEN 'RNO'
    WHEN 'ETE1' THEN 'RNO'
    WHEN 'PAR1' THEN 'RNO'
    WHEN 'DU12' THEN 'RNO'
    WHEN 'GGT1' THEN 'RNO'
    WHEN 'AK11' THEN 'RNO'
    WHEN 'BT99' THEN 'RNO'
    WHEN 'KES1' THEN 'RNO'
    WHEN 'LED6' THEN 'RNO'
    WHEN 'BL13' THEN 'RNO'
    WHEN 'MJ11' THEN 'RNO'
    WHEN 'JT11' THEN 'RNO'
    WHEN 'FLC1' THEN 'RNO'
    WHEN 'TEM1' THEN 'RNO'
    WHEN 'BBJ1' THEN 'RNO'
    WHEN 'RUB1' THEN 'RNO'
    WHEN 'GE15' THEN 'RNO'
    WHEN 'HT12' THEN 'RNO'
    WHEN 'RT11' THEN 'RNO'
    WHEN 'BT22' THEN 'RNO'
    WHEN 'BN01' THEN 'RNO'
    WHEN 'LWT1' THEN 'RNO'
    WHEN 'EJ11' THEN 'RNO'
    WHEN 'PAV1' THEN 'RNO'
    WHEN 'JCX1' THEN 'RNO'
    WHEN 'KNN1' THEN 'RNO'
    WHEN 'CT23' THEN 'RNO'
    WHEN 'PE22' THEN 'RNO'
    WHEN 'DT22' THEN 'RNO'
    WHEN 'HSD1' THEN 'RNO'
    WHEN 'MPH1' THEN 'RNO'
    WHEN 'GE13' THEN 'RNO'
    WHEN 'FCL1' THEN 'RNO'
    WHEN '2BG1' THEN 'RNO'
    WHEN 'KC22' THEN 'RNO'
    WHEN 'IBM1' THEN 'RNO'
    WHEN 'DTG1' THEN 'RNO'
    WHEN 'MBT1' THEN 'RNO'
    WHEN 'LD19' THEN 'RNO'
    WHEN 'LED2' THEN 'RNO'
    WHEN 'GF11' THEN 'RNO'
    WHEN 'ME55' THEN 'RNO'
    WHEN 'RSF2' THEN 'RNO'
    WHEN 'GO13' THEN 'RNO'
    WHEN 'CC22' THEN 'RNO'
    WHEN 'NSL2' THEN 'RNO'
    WHEN 'KNN3' THEN 'RNO'
    WHEN 'ST45' THEN 'RNO'
    WHEN 'UT11' THEN 'RNO'
    WHEN 'WHE2' THEN 'RNO'
    WHEN 'DTG4' THEN 'RNO'
    WHEN 'DU15' THEN 'RNO'
    WHEN 'DTG5' THEN 'RNO'
    WHEN 'ID22' THEN 'RNO'
    WHEN 'NE11' THEN 'RNO'
    WHEN 'WHE3' THEN 'RNO'
    WHEN 'AVA1' THEN 'RNO'
    WHEN 'BL11' THEN 'RNO'
    WHEN 'HF11' THEN 'RNO'
    WHEN 'CS55' THEN 'RNO'
    WHEN 'LED7' THEN 'RNO'
    WHEN 'THT1' THEN 'RNO'
    WHEN 'RSF1' THEN 'RNO'
    WHEN 'AT66' THEN 'RNO'
    WHEN 'OT22' THEN 'RNO'
    WHEN 'CXT1' THEN 'RNO'
    WHEN 'BAB1' THEN 'RNO'
    WHEN 'JR55' THEN 'RNO'
    WHEN 'DU11' THEN 'RNO'
    WHEN 'NT01' THEN 'RNO'
    WHEN 'DEL0' THEN 'RNO'
    WHEN '3GEN' THEN 'RNO'
    WHEN 'RN01' THEN 'RNO'
    WHEN 'RN02' THEN 'RNO'
    WHEN 'RN03' THEN 'RNO'
    WHEN 'TCC2' THEN 'RNO'
    WHEN 'DU14' THEN 'RNO'
    WHEN 'AV11' THEN 'RNO'
    WHEN 'SL33' THEN 'RNO'
    WHEN 'VV11' THEN 'RNO'
    WHEN 'TT22' THEN 'RNO'
    WHEN 'PX11' THEN 'RNO'
    WHEN 'CT22' THEN 'RNO'
    WHEN 'UE55' THEN 'RNO'
    WHEN 'USA2' THEN 'RNO'
    WHEN 'LED1' THEN 'RNO'
    WHEN 'GE10' THEN 'RNO'
    WHEN 'GF12' THEN 'RNO'
    WHEN 'GG11' THEN 'RNO'
    WHEN 'BT12' THEN 'RNO'
    WHEN 'LED5' THEN 'RNO'
    WHEN 'GE12' THEN 'RNO'
    WHEN 'HB13' THEN 'RNO'
    WHEN 'NF11' THEN 'RNO'
    WHEN 'JTS1' THEN 'RNO'
    WHEN 'GTI1' THEN 'RNO'
    WHEN 'TT11' THEN 'RNO'
    WHEN 'CT11' THEN 'RNO'
    WHEN 'IT55' THEN 'RNO'
    WHEN 'ET11' THEN 'RNO'
    WHEN 'AK13' THEN 'RNO'
    WHEN 'NL11' THEN 'RNO'
    WHEN 'NSL1' THEN 'RNO'
    WHEN 'BR11' THEN 'RNO'
    WHEN 'GLT1' THEN 'RNO'
    WHEN 'LINN' THEN 'RNO'
    WHEN 'NST1' THEN 'RNO'
    WHEN 'TCE1' THEN 'RNO'
    WHEN 'ST11' THEN 'RNO'
    WHEN 'WHE1' THEN 'RNO'
    WHEN 'TCC3' THEN 'RNO'
    WHEN 'HF55' THEN 'RNO'
    WHEN 'GX11' THEN 'RNO'
    WHEN 'RL23' THEN 'RNO'
    WHEN 'HF01' THEN 'RNO'
    WHEN 'SGY1' THEN 'RNO'
    WHEN 'BH11' THEN 'RNO'
    WHEN 'AS11' THEN 'RNO'
    WHEN 'RO01' THEN 'ROW'
    WHEN 'RO02' THEN 'ROW'
    WHEN 'RO03' THEN 'ROW'
    WHEN 'DE22' THEN 'RPC'
    WHEN 'YAT1' THEN 'RPC'
    WHEN 'RP01' THEN 'RPC'
    WHEN 'RP02' THEN 'RPC'
    WHEN 'RP03' THEN 'RPC'
    WHEN 'SN01' THEN 'SAL'
    WHEN 'SN02' THEN 'SAL'
    WHEN 'SN03' THEN 'SAL'
    WHEN 'PP11' THEN 'SAT'
    WHEN 'FLY3' THEN 'SCB'
    WHEN 'FLY2' THEN 'SCB'
    WHEN 'FLY1' THEN 'SCB'
    WHEN 'SC01' THEN 'SCB'
    WHEN 'SC02' THEN 'SCB'
    WHEN 'SC03' THEN 'SCB'
    WHEN 'BRR1' THEN 'SCB'
    WHEN 'TSF1' THEN 'SCB'
    WHEN 'SK03' THEN 'SCK'
    WHEN 'EXC1' THEN 'SGF'
    WHEN 'ZBE1' THEN 'SGF'
    WHEN 'ELF1' THEN 'SGF'
    WHEN 'HK11' THEN 'SGF'
    WHEN 'IGT1' THEN 'SGF'
    WHEN 'DMK1' THEN 'SGF'
    WHEN 'UND1' THEN 'SGF'
    WHEN 'ARB1' THEN 'SGF'
    WHEN 'FAL1' THEN 'SGF'
    WHEN 'SF02' THEN 'SGF'
    WHEN 'SF03' THEN 'SGF'
    WHEN 'FT11' THEN 'SGF'
    WHEN 'VHL1' THEN 'SGF'
    WHEN 'ZBE2' THEN 'SGF'
    WHEN 'PJT1' THEN 'SGF'
    WHEN 'SG01' THEN 'SGU'
    WHEN 'SG02' THEN 'SGU'
    WHEN 'SG03' THEN 'SGU'
    WHEN 'CC11' THEN 'SLC'
    WHEN 'BES1' THEN 'SLC'
    WHEN 'SDA1' THEN 'SLC'
    WHEN 'CBT2' THEN 'SLC'
    WHEN 'CZ01' THEN 'SLC'
    WHEN 'L701' THEN 'SLC'
    WHEN 'ML17' THEN 'SLC'
    WHEN 'ML30' THEN 'SLC'
    WHEN 'RAW5' THEN 'SLC'
    WHEN 'IV11' THEN 'SLC'
    WHEN 'RD02' THEN 'SLC'
    WHEN 'ML40' THEN 'SLC'
    WHEN 'ML31' THEN 'SLC'
    WHEN 'RD01' THEN 'SLC'
    WHEN 'RAW4' THEN 'SLC'
    WHEN 'LF02' THEN 'SLC'
    WHEN 'ML04' THEN 'SLC'
    WHEN 'ML14' THEN 'SLC'
    WHEN 'ML08' THEN 'SLC'
    WHEN 'ME33' THEN 'SLC'
    WHEN 'RAW9' THEN 'SLC'
    WHEN 'CZ02' THEN 'SLC'
    WHEN 'ARI3' THEN 'SLC'
    WHEN 'CZ05' THEN 'SLC'
    WHEN 'WL02' THEN 'SLC'
    WHEN 'GAM1' THEN 'SLC'
    WHEN 'DTM1' THEN 'SLC'
    WHEN 'USA1' THEN 'SLC'
    WHEN 'RD03' THEN 'SLC'
    WHEN 'SL09' THEN 'SLC'
    WHEN 'RAW7' THEN 'SLC'
    WHEN 'LF01' THEN 'SLC'
    WHEN 'CZ06' THEN 'SLC'
    WHEN 'RAW0' THEN 'SLC'
    WHEN 'ARC1' THEN 'SLC'
    WHEN 'ATL1' THEN 'SLC'
    WHEN 'RAW2' THEN 'SLC'
    WHEN 'KMB1' THEN 'SLC'
    WHEN 'KSP1' THEN 'SLC'
    WHEN 'CU01' THEN 'SLC'
    WHEN 'CZ03' THEN 'SLC'
    WHEN 'BHU1' THEN 'SLC'
    WHEN 'SL21' THEN 'SLC'
    WHEN 'ML10' THEN 'SLC'
    WHEN 'KMB2' THEN 'SLC'
    WHEN 'RAW8' THEN 'SLC'
    WHEN 'MLT1' THEN 'SLC'
    WHEN 'MLT2' THEN 'SLC'
    WHEN 'MLT3' THEN 'SLC'
    WHEN 'MLT4' THEN 'SLC'
    WHEN 'MA02' THEN 'SLC'
    WHEN 'JUG1' THEN 'SLC'
    WHEN 'NEW2' THEN 'SLC'
    WHEN 'RAW1' THEN 'SLC'
    WHEN 'CBT1' THEN 'SLC'
    WHEN 'RS11' THEN 'SLC'
    WHEN 'HAL1' THEN 'SLC'
    WHEN 'MET1' THEN 'SLC'
    WHEN 'ML09' THEN 'SLC'
    WHEN 'USC3' THEN 'SLC'
    WHEN 'USC2' THEN 'SLC'
    WHEN 'SLR1' THEN 'SLC'
    WHEN 'ML06' THEN 'SLC'
    WHEN 'RAW3' THEN 'SLC'
    WHEN 'ML32' THEN 'SLC'
    WHEN 'SL13' THEN 'SLC'
    WHEN 'HTS1' THEN 'SPK'
    WHEN 'WOR2' THEN 'SPK'
    WHEN 'WO01' THEN 'SPK'
    WHEN 'NAT1' THEN 'STL'
    WHEN 'FUG1' THEN 'STL'
    WHEN 'HS11' THEN 'STL'
    WHEN 'CWK8' THEN 'STL'
    WHEN 'WA11' THEN 'STL'
    WHEN 'HIC1' THEN 'STL'
    WHEN 'CWK3' THEN 'STL'
    WHEN 'CWK2' THEN 'STL'
    WHEN 'CWK1' THEN 'STL'
    WHEN 'RR03' THEN 'STL'
    WHEN 'CWK5' THEN 'STL'
    WHEN 'HRT1' THEN 'STL'
    WHEN 'CAR1' THEN 'STL'
    WHEN 'SAF2' THEN 'STL'
    WHEN 'NW11' THEN 'STL'
    WHEN 'SAF1' THEN 'STL'
    WHEN 'LP11' THEN 'STL'
    WHEN 'ZT11' THEN 'STL'
    WHEN 'ZHA1' THEN 'STL'
    WHEN 'MA12' THEN 'STL'
    WHEN 'HUM3' THEN 'STL'
    WHEN 'AT11' THEN 'STL'
    WHEN 'CWK7' THEN 'STL'
    WHEN 'MEL1' THEN 'STL'
    WHEN 'HUM1' THEN 'STL'
    WHEN 'GFS2' THEN 'STL'
    WHEN 'ZIY2' THEN 'STL'
    WHEN 'HH22' THEN 'STL'
    WHEN 'FR11' THEN 'STL'
    WHEN 'AKA1' THEN 'STL'
    WHEN 'GFS1' THEN 'STL'
    WHEN 'RIP1' THEN 'STL'
    WHEN 'MA77' THEN 'STL'
    WHEN 'HIC2' THEN 'STL'
    WHEN 'STL0' THEN 'STL'
    WHEN 'CWK6' THEN 'STL'
    WHEN 'DB11' THEN 'STL'
    WHEN 'GA22' THEN 'STL'
    WHEN 'CWK4' THEN 'STL'
    WHEN 'ACE1' THEN 'SXF'
    WHEN 'WT24' THEN 'SXF'
    WHEN 'WT14' THEN 'SXF'
    WHEN 'WIT6' THEN 'SXF'
    WHEN 'WT32' THEN 'SXF'
    WHEN 'NA83' THEN 'SXF'
    WHEN 'WIT9' THEN 'SXF'
    WHEN 'XFR6' THEN 'SXF'
    WHEN 'BTLRSXF' THEN 'SXF'
    WHEN 'XFR1' THEN 'SXF'
    WHEN 'WT31' THEN 'SXF'
    WHEN 'WT27' THEN 'SXF'
    WHEN 'WT35' THEN 'SXF'
    WHEN 'GST2' THEN 'SXF'
    WHEN 'CKH1' THEN 'SXF'
    WHEN 'WIT5' THEN 'SXF'
    WHEN 'WIT7' THEN 'SXF'
    WHEN 'WT33' THEN 'SXF'
    WHEN 'WIT4' THEN 'SXF'
    WHEN 'WIT3' THEN 'SXF'
    WHEN 'WIT8' THEN 'SXF'
    WHEN 'DTR1' THEN 'SXF'
    WHEN 'CKH2' THEN 'SXF'
    WHEN 'DE33' THEN 'SXF'
    WHEN 'WXP2' THEN 'SXF'
    WHEN 'XFR7' THEN 'SXF'
    WHEN 'XFR8' THEN 'SXF'
    WHEN 'WC11' THEN 'SXF'
    WHEN 'GST1' THEN 'SXF'
    WHEN 'WIT2' THEN 'SXF'
    WHEN 'JD11' THEN 'SXF'
    WHEN 'JMB1' THEN 'SXF'
    WHEN 'DXP1' THEN 'SXF'
    WHEN 'WIT1' THEN 'SXF'
    WHEN 'XFR5' THEN 'SXF'
    WHEN 'UG33' THEN 'SXF'
    WHEN 'WXP1' THEN 'SXF'
    WHEN 'WT30' THEN 'SXF'
    WHEN 'WT22' THEN 'SXF'
    WHEN 'MCH1' THEN 'SXF'
    WHEN 'XFR2' THEN 'SXF'
    WHEN 'CHH1' THEN 'SXF'
    WHEN 'WTT0' THEN 'SXF'
    WHEN 'WT26' THEN 'SXF'
    WHEN 'HAM1' THEN 'SXF'
    WHEN 'EA22' THEN 'SXF'
    WHEN 'WT28' THEN 'SXF'
    WHEN 'WT23' THEN 'SXF'
    WHEN 'XFR4' THEN 'SXF'
    WHEN 'WT11' THEN 'SXF'
    WHEN 'SX01' THEN 'SXF'
    WHEN 'SX02' THEN 'SXF'
    WHEN 'SX03' THEN 'SXF'
    WHEN 'SX04' THEN 'SXF'
    WHEN 'SX05' THEN 'SXF'
    WHEN 'SX06' THEN 'SXF'
    WHEN 'SX07' THEN 'SXF'
    WHEN 'SX08' THEN 'SXF'
    WHEN 'SX09' THEN 'SXF'
    WHEN 'WT15' THEN 'SXF'
    WHEN 'LB11' THEN 'SXF'
    WHEN 'WIT0' THEN 'SXF'
    WHEN 'WT13' THEN 'SXF'
    WHEN 'WT36' THEN 'SXF'
    WHEN 'WT25' THEN 'SXF'
    WHEN 'XFRX' THEN 'SXF'
    WHEN 'TU01' THEN 'TUS'
    WHEN 'TU02' THEN 'TUS'
    WHEN 'TU03' THEN 'TUS'
    WHEN 'FB11' THEN 'WIC'
    WHEN 'IND1' THEN 'WIC'
    WHEN 'ID11' THEN 'WIC'
    WHEN 'TRT5' THEN 'WIC'
    WHEN 'TRT6' THEN 'WIC'
    WHEN 'OTM1' THEN 'WIC'
    WHEN 'MFF2' THEN 'WIC'
    WHEN 'TRT7' THEN 'WIC'
    WHEN 'PL13' THEN 'WIC'
    WHEN 'ASA1' THEN 'WIC'
    WHEN 'PID1' THEN 'WIC'
    WHEN 'TOL1' THEN 'WIC'
    WHEN 'MED2' THEN 'WIC'
    WHEN 'TRT0' THEN 'WIC'
    WHEN 'TL11' THEN 'WIC'
    WHEN 'ASA2' THEN 'WIC'
    WHEN 'PL12' THEN 'WIC'
    WHEN 'NAR1' THEN 'WIC'
    WHEN 'TRT3' THEN 'WIC'
    WHEN 'OR11' THEN 'WIC'
    WHEN 'JSM1' THEN 'WIC'
    WHEN 'KE22' THEN 'WIC'
    WHEN 'TRT8' THEN 'WIC'
    WHEN 'MWI1' THEN 'WIC'
    WHEN 'MWR1' THEN 'WIC'
    WHEN 'TRS4' THEN 'WIC'
    WHEN 'NOV1' THEN 'WIC'
    WHEN 'TRT1' THEN 'WIC'
    WHEN 'BIS1' THEN 'WIC'
    WHEN 'MED1' THEN 'WIC'
    WHEN 'MED3' THEN 'WIC'
    WHEN 'LON1' THEN 'WIC'
    WHEN 'WIC4' THEN 'WIC'
    WHEN 'WIC3' THEN 'WIC'
    WHEN 'STS4' THEN 'WIC'
    WHEN 'CT88' THEN 'WIC'
    WHEN 'TRT4' THEN 'WIC'
    WHEN 'IT11' THEN 'WIC'
    WHEN 'NA69' THEN 'WIC'
    WHEN 'WIC6' THEN 'WIC'
    WHEN 'MUN1' THEN 'WIC'
    WHEN 'SEF1' THEN 'WIC'
    WHEN 'GA11' THEN 'WIC'
    WHEN 'IT12' THEN 'WIC'
    WHEN 'TRT2' THEN 'WIC'
    WHEN 'TRT9' THEN 'WIC'
    WHEN 'LIB1' THEN 'WIC'
    WHEN 'TWS1' THEN 'WIC'
    WHEN 'MFF1' THEN 'WIC'
    WHEN 'NOV2' THEN 'WIC'
    WHEN 'PL11' THEN 'WIC'
    WHEN 'MWF1' THEN 'WIC'
    WHEN 'WIC5' THEN 'WIC'
    WHEN 'WI01' THEN 'WIC'
    WHEN 'WI02' THEN 'WIC'
    WHEN 'WI03' THEN 'WIC'
    WHEN 'NOV3' THEN 'WIC'
    WHEN 'JEB1' THEN 'WTT'
    WHEN 'WT01' THEN 'WTT'
    WHEN 'WT02' THEN 'WTT'
    WHEN 'WT03' THEN 'WTT'
    ELSE "homeTerminalCode"
  END
WHERE "externalDriverId" IN (
  'ZT02',
  'BLK4',
  'AB03',
  'BK12',
  'BK13',
  'ZB01',
  'ZT01',
  'BLK9',
  'BLK2',
  'ZT04',
  'RA02',
  'BK16',
  'HSS1',
  'HSS2',
  'HSS3',
  'ZT05',
  'ZT03',
  'BK14',
  'ABX1',
  'BK15',
  'BLK1',
  'BLK6',
  'RA01',
  'BLK5',
  'BLK0',
  'BK11',
  'ZT06',
  'BLK8',
  'BLK7',
  'BIL1',
  'BL01',
  'BL02',
  'BL03',
  'BT44',
  'CT56',
  'RPR1',
  'GF50',
  'CT55',
  'CT57',
  'AP11',
  'APM1',
  'PC11',
  'R304',
  'R3X1',
  'R301',
  'PC22',
  'R302',
  'R303',
  'WS01',
  'DT33',
  'BI01',
  'BI02',
  'BI03',
  'BTLRBIS',
  'TIN1',
  'B104',
  'BT55',
  'TIN2',
  'BO01',
  'BO02',
  'BO03',
  'BT01',
  'BT02',
  'BT03',
  'OL91',
  'BY01',
  'BY02',
  'BY03',
  'BZ01',
  'BZ02',
  'BZ03',
  'CA01',
  'CA02',
  'CA03',
  'DCB1',
  'JC12',
  'GT42',
  'GT16',
  'GT14',
  'ALI1',
  'RED2',
  'EA01',
  'ROY0',
  'RB24',
  'RB20',
  'GTZ5',
  'COL2',
  'GT39',
  'DN01',
  'DN02',
  'DN03',
  'GT44',
  'EDK1',
  'OOES',
  'REL3',
  'GT22',
  'GTZ7',
  'GT41',
  'GTZ9',
  'GT33',
  'EA02',
  'EA05',
  'RED5',
  'EA10',
  'GT38',
  'EA09',
  'JR26',
  'AZK1',
  'ROY3',
  'GT12',
  'ROY1',
  'EA03',
  'RB22',
  'GT30',
  'HGX1',
  'HGX2',
  'HGX3',
  'GT40',
  'GT24',
  'GT35',
  'GT20',
  'TWT1',
  'JR22',
  'RB25',
  'MT11',
  'GT15',
  'RED6',
  'RB15',
  'EA12',
  'GTZ8',
  'GT31',
  'GT37',
  'RED1',
  'GT34',
  'GT48',
  'GT36',
  'NA11',
  'NA10',
  'GTZ4',
  'GT26',
  'GT21',
  'NA16',
  'GTZ2',
  'GT25',
  'EA06',
  'REL2',
  'JR25',
  'GT18',
  'PER3',
  'CT02',
  'GT19',
  'REL5',
  'RB13',
  'QST1',
  'JR23',
  'GT50',
  'GT45',
  'COL1',
  'GT10',
  'DEN1',
  'DEN2',
  'GTZ3',
  'PER1',
  'PER2',
  'PER4',
  'REB1',
  'DEN3',
  'QKS1',
  'QKS2',
  'GT23',
  'GTZ6',
  'GT47',
  'GT29',
  'EA04',
  'GT27',
  'RM12',
  'RM13',
  'RMF1',
  'RM10',
  'RMF2',
  'RMF3',
  'RMF4',
  'RMF5',
  'RMF6',
  'RMF7',
  'RMF8',
  'RB21',
  'EA08',
  'OORS',
  'JQ11',
  'GT28',
  'EA07',
  'RED3',
  'GMT1',
  'STP1',
  'TQL1',
  'TQL2',
  'TQL3',
  'TQL4',
  'TQL5',
  'TRI1',
  'TRI2',
  'GTZ1',
  'GTZ0',
  'COL3',
  'GT32',
  'SDE1',
  'TUT1',
  'DAN1',
  'MJW1',
  'ECO1',
  'ML29',
  'QS01',
  'QS02',
  'QS03',
  'DF01',
  'DF02',
  'DF03',
  'EMJ1',
  'ML24',
  'ML28',
  'ML27',
  'DEL5',
  'ME12',
  'MAX1',
  'BRA2',
  'SL55',
  'ME11',
  'BRA1',
  'MJW4',
  'MJW2',
  'ME13',
  'RAJ1',
  'MJW3',
  'KCF1',
  'HT33',
  'PLP1',
  'ML26',
  'FLA1',
  'ML23',
  'ML22',
  'VR11',
  'ML25',
  'SS77',
  'DI01',
  'DI02',
  'DI03',
  'DOD1',
  'DR01',
  'DR02',
  'DR03',
  'UNO1',
  'USR1',
  'ACD1',
  'ACD2',
  'BIN1',
  'BIN3',
  'SPA1',
  'BIN4',
  'AMM1',
  'ELG1',
  'DD12',
  'DRA1',
  'NA03',
  'KK02',
  'KEM1',
  'SAB3',
  'NA87',
  'DS01',
  'DS02',
  'DS03',
  'TW01',
  'DD11',
  'FRO1',
  'KK04',
  'RJ02',
  'FR01',
  'FR02',
  'UNT1',
  'SWT1',
  'RJ01',
  'LEA1',
  'NA86',
  'KK03',
  'TW03',
  'KK07',
  'KK01',
  'NA88',
  'TW02',
  'KK05',
  'PTL1',
  'BIN2',
  'DD13',
  'NA04',
  'OL84',
  'OL85',
  'OL99',
  'KK06',
  'PDS1',
  'RJ03',
  'RJ04',
  'BX01',
  'RJ05',
  'SWT3',
  'NA90',
  'VE11',
  'NA89',
  'TW04',
  'TW05',
  'NA91',
  'DU01',
  'DU02',
  'DU03',
  '764Z',
  '764Y',
  'JOY1',
  '764X',
  'EL01',
  'EL02',
  'EL03',
  '764G',
  'DJE1',
  '764N',
  '764H',
  '764K',
  'JFT1',
  '764C',
  '764J',
  'GNS1',
  'TP01',
  '764F',
  '764M',
  'S601',
  'NAI1',
  'TRW4',
  'BTLRFAR',
  'BTLRJMS',
  'FA01',
  'FA02',
  'FA03',
  'TRW3',
  'TRW1',
  'SCF1',
  'MAN1',
  'MAN2',
  'MAN3',
  'TRW2',
  'NA65',
  'OL05',
  'OL12',
  'OL13',
  'OL14',
  'OL16',
  'OL17',
  'OL19',
  'OL22',
  'OL25',
  'OL30',
  'OL31',
  'OL35',
  'OL36',
  'OL37',
  'OL38',
  'OL44',
  'OL46',
  'OL51',
  'OL63',
  'OL64',
  'OL65',
  'OL68',
  'OL69',
  'OL71',
  'OL76',
  'OL77',
  'OL79',
  'OL80',
  'OL81',
  'OL82',
  'OL83',
  'OL88',
  'OL89',
  'OL90',
  'OL92',
  'OL93',
  'OL94',
  'OL95',
  'OL96',
  'OL97',
  'OL98',
  'OLX1',
  'OL01',
  'OL10',
  'OL11',
  'OL15',
  'OL02',
  'OL20',
  'OL21',
  'OL23',
  'OL24',
  'OL26',
  'OL27',
  'OL28',
  'OL29',
  'OL03',
  'OL32',
  'OL33',
  'OL34',
  'OL04',
  'OL06',
  'OL66',
  'OL07',
  'OL08',
  'OL09',
  'OLT1',
  'OWS1',
  'AW11',
  'NRE1',
  'HH24',
  'SCF2',
  'FO01',
  'FO02',
  'FO03',
  'GA01',
  'GA02',
  'GA03',
  'GF01',
  'GF02',
  'GF03',
  'GJ01',
  'GJ02',
  'GJ03',
  'SPL1',
  'GI01',
  'GI02',
  'GI03',
  'JEC1',
  'GT01',
  'GT02',
  'GT03',
  'LH01',
  'HY01',
  'HY02',
  'HY03',
  'HAY1',
  'ST88',
  'HH25',
  'GF55',
  'ST77',
  'AKA2',
  'HO02',
  'HO03',
  'ST44',
  'ST99',
  'LT11',
  'ZT12',
  'ST75',
  'ST55',
  'ID01',
  'ID02',
  'ID03',
  'IOL1',
  '247E',
  'RNA1',
  'RE55',
  'USC4',
  'GE44',
  'SET2',
  'HH23',
  'JR04',
  'SS05',
  'SS12',
  'ARM1',
  'ARM2',
  'ARM3',
  'NA76',
  'KEE1',
  'JLL1',
  'DE15',
  'JAS1',
  'KE11',
  'QUI3',
  'TUT2',
  'ST66',
  'KEE6',
  'SAM1',
  'JRS1',
  'SS16',
  'SS04',
  'PROC',
  'VR22',
  'PROK',
  'FA11',
  'DKT1',
  'RR11',
  'SS14',
  'DE34',
  'BLE1',
  'DEL2',
  'HET2',
  'PR45',
  'CR11',
  'SS02',
  'TRL2',
  'HA11',
  'KEE7',
  'PHA1',
  'NAX7',
  'GBT1',
  'LTN1',
  'DE55',
  'ASK1',
  'ST22',
  'QUI1',
  'DAH1',
  'VKT1',
  'KAG1',
  'SS15',
  'JR01',
  'SS06',
  'BHP2',
  'SS17',
  'JR06',
  'SS10',
  'TRKN',
  'JR02',
  'DEL9',
  'KC01',
  'KC02',
  'KC03',
  'TRJN',
  'QUI4',
  'UNI1',
  'TRLY',
  'AJ01',
  'TRL3',
  'PROT',
  'TR1L',
  'JR03',
  'AJ02',
  'HH11',
  'SS07',
  'EA11',
  'KL11',
  'DEL7',
  'SS11',
  'MIK1',
  'KEE4',
  'QUI5',
  'MEC1',
  'KEE3',
  'SEE1',
  'NWE1',
  'ATZ1',
  '3BM1',
  'NEL1',
  'SS09',
  'EG11',
  'SET3',
  'DC11',
  'AAM1',
  'LKR1',
  'SS01',
  'PAW1',
  'TRRY',
  'QKSL',
  'HH27',
  'HET1',
  'RW11',
  'KE55',
  'UT12',
  'QUI2',
  'PAM1',
  'TJ11',
  'QU02',
  'LEA2',
  'CPT1',
  'SS08',
  'NA49',
  'BAR1',
  'JR05',
  'TR2L',
  'USL1',
  'KEE8',
  'SPR1',
  'GL11',
  'SHE1',
  'AZW1',
  'UG11',
  'BRG1',
  'KS01',
  'KS02',
  'KS03',
  'RM11',
  'FS20',
  'GE01',
  'ARP1',
  'SP11',
  'GD15',
  'AL11',
  'MF11',
  'BST1',
  'BST2',
  'BST3',
  'TRA1',
  'CE11',
  'FS15',
  'GS25',
  'LTD1',
  'GS20',
  'DGT1',
  'GS11',
  'FS22',
  'EG55',
  'FIN1',
  'BER1',
  'ME22',
  'LK02',
  'AP22',
  'BER2',
  'EW11',
  'CH11',
  'OGR1',
  'GS14',
  'GS22',
  'INL1',
  'GS21',
  'FS21',
  'FS24',
  'AT88',
  'GS30',
  'FS13',
  'RE11',
  'GRV1',
  'GD17',
  'LL10',
  'LT55',
  'DRT9',
  'HGH1',
  'LL11',
  'LA01',
  'LA02',
  'LA03',
  'GS15',
  'CAP1',
  'FS18',
  'GS29',
  'GS19',
  'HKT1',
  'LK01',
  'JAC1',
  'TH02',
  'FT33',
  'NE55',
  'TH03',
  'GS27',
  'GS28',
  'GD12',
  'GS23',
  'AB11',
  'GS12',
  'TH01',
  'GD13',
  'ARI2',
  'ARI1',
  'AEO1',
  'GD16',
  'SP12',
  'BER3',
  'AZA1',
  'GS13',
  'FS14',
  'GS24',
  'GS16',
  'FS12',
  'GD11',
  'GD14',
  'FS11',
  'FS23',
  'GS17',
  'FOR1',
  'JG11',
  'LB01',
  'LB02',
  'LB03',
  'WRT1',
  'TF55',
  'BTLRMOT',
  'TF11',
  'SS55',
  'TF22',
  'JRY1',
  'TF33',
  'MO01',
  'MO02',
  'MO03',
  'TF44',
  'BOO2',
  'MI01',
  'MI02',
  'MI03',
  'BOO1',
  'TCF7',
  'GE22',
  'SK02',
  'RL13',
  'HH26',
  'EXP1',
  'WAL1',
  'SE22',
  'TC11',
  'RC01',
  'EYL1',
  'TCF3',
  'TCF6',
  'BU11',
  'PL33',
  'LE11',
  'DE11',
  'TT01',
  'DE10',
  'HAT1',
  'FRL1',
  'FFS1',
  'MVP6',
  'ELT1',
  'RL12',
  'TCF9',
  'RL11',
  'OZB1',
  'NA35',
  'NA02',
  'OL74',
  'SK01',
  'CCP1',
  'LOT1',
  'LOT2',
  'MVP3',
  'AVC1',
  'FL11',
  'OL75',
  'SAT1',
  'MON1',
  'MON2',
  'MON3',
  'TCF2',
  'WWH1',
  'OL18',
  'OL39',
  'OL45',
  'OL70',
  'OL72',
  'OL73',
  'OL86',
  'OL87',
  'OLM2',
  'OLM1',
  'OLM3',
  'OLM4',
  'OLM5',
  'OLM6',
  'OLM9',
  'OL40',
  'OL42',
  'TCF5',
  'RUN1',
  'PCE1',
  'PRO1',
  'PRO2',
  'PRO3',
  'PRO4',
  'PRO5',
  'PRO6',
  'PRO7',
  'PRO8',
  'PRO9',
  'DEL1',
  'DE12',
  'RCG1',
  'FT22',
  'CLE1',
  'TCF1',
  'MVP2',
  'TOT1',
  'TOT0',
  'TOT2',
  'TOT3',
  'TOT4',
  'TOT5',
  'TOT6',
  'TOT7',
  'TOT8',
  'TOT9',
  'DE13',
  'TTS1',
  'TCS1',
  'TCS0',
  'TCS2',
  'TCS3',
  'TCS4',
  'TCS5',
  'TCS6',
  'TCS7',
  'TCS8',
  'TCS9',
  'ACT3',
  'TCF4',
  'TCF8',
  'NC01',
  'NC02',
  'NC03',
  'CT01',
  'NA22',
  'WAY1',
  'NP01',
  'NP02',
  'NP03',
  'MOO4',
  'TUT3',
  'MOO1',
  'ATT1',
  'MO17',
  'CST1',
  'MO11',
  'IBR1',
  'NA60',
  'MOO6',
  'HIL2',
  'HIL1',
  'HIL3',
  'SLA3',
  'MO12',
  'OT12',
  'MO16',
  'SLA4',
  'SLA2',
  'JJT3',
  'JJT2',
  'JJT1',
  'MOO7',
  'NA64',
  'KRA1',
  'MOO2',
  'OT14',
  'STL1',
  'MOO9',
  'SILD',
  'JN01',
  'OO01',
  'OO02',
  'OM01',
  'OM02',
  'OM03',
  'MO15',
  'PRD1',
  'PRD2',
  'PRD3',
  'NTS1',
  'NA05',
  'MOO5',
  'MOO3',
  'OT15',
  'MO13',
  'OT11',
  'LAS1',
  'TLC1',
  'SNL1',
  'OT16',
  'MOO8',
  'OT13',
  'TRL1',
  'SLA1',
  'BM11',
  'WTT1',
  'FAL2',
  'ON03',
  '3K03',
  'PFH5',
  'PF14',
  'BS01',
  'BS02',
  'BS03',
  'PFH4',
  'STH1',
  'PFH2',
  'RW01',
  'DD01',
  'EMM1',
  'PFH9',
  'AZD1',
  'PF12',
  'JET1',
  '3K05',
  '3K01',
  'EMM2',
  'TGT1',
  '3K04',
  'PFH7',
  'JET3',
  'ARA1',
  'JET2',
  'UP01',
  'PFH3',
  'PFH6',
  'PF11',
  'RTR1',
  'USC1',
  'SCT1',
  'ONE7',
  'EMM3',
  'PFH1',
  'DDP1',
  'PH01',
  'PH02',
  'PH03',
  'PH04',
  'PH05',
  'PH06',
  'PH07',
  'PH08',
  'PH09',
  'PH10',
  'PH11',
  'PH12',
  'PH13',
  'PH14',
  'PH15',
  '3K02',
  'ONE1',
  'ONE4',
  'ONE3',
  'ONE2',
  'ONE5',
  'SWT2',
  'ONE6',
  'PI01',
  'PI02',
  'PI03',
  'GTP3',
  'GTP4',
  'GTP1',
  'GTP5',
  'GTP2',
  'PER5',
  'PER6',
  'PU01',
  'PU02',
  'PU03',
  'ZA11',
  'CB11',
  'HB11',
  'KNN2',
  'TA11',
  'ABR1',
  'GTI2',
  'USK1',
  'USK2',
  'BC22',
  'LED8',
  'TCE2',
  'DTG2',
  'TCC1',
  'EE11',
  'SKY3',
  'RF01',
  'SE11',
  'RL22',
  'BSG1',
  'BHF1',
  'KTL1',
  'GO12',
  'GO11',
  'TU11',
  'TT12',
  'ST33',
  'JT15',
  'JT12',
  'DT44',
  'AT55',
  'GF13',
  'BP11',
  'BST4',
  'BST5',
  'BST6',
  'BC11',
  'TEM2',
  'GEN5',
  'TLF1',
  'KG22',
  'GE20',
  'TCE3',
  'LE22',
  'DBN1',
  'BMT1',
  'GFM1',
  'MDS1',
  'BT11',
  'GE11',
  'NL22',
  'ALP1',
  'VL11',
  'ELD1',
  'PE11',
  'WT44',
  'AK12',
  'DU13',
  'LED3',
  'KC11',
  'GST3',
  'LE25',
  'DTG3',
  'LED4',
  'RL25',
  'NT55',
  'JNM1',
  'MA55',
  'AQ11',
  'BL12',
  'MGT1',
  'KL55',
  'GEN2',
  'RL24',
  'ETE1',
  'PAR1',
  'DU12',
  'GGT1',
  'AK11',
  'BT99',
  'KES1',
  'LED6',
  'BL13',
  'MJ11',
  'JT11',
  'FLC1',
  'TEM1',
  'BBJ1',
  'RUB1',
  'GE15',
  'HT12',
  'RT11',
  'BT22',
  'BN01',
  'LWT1',
  'EJ11',
  'PAV1',
  'JCX1',
  'KNN1',
  'CT23',
  'PE22',
  'DT22',
  'HSD1',
  'MPH1',
  'GE13',
  'FCL1',
  '2BG1',
  'KC22',
  'IBM1',
  'DTG1',
  'MBT1',
  'LD19',
  'LED2',
  'GF11',
  'ME55',
  'RSF2',
  'GO13',
  'CC22',
  'NSL2',
  'KNN3',
  'ST45',
  'UT11',
  'WHE2',
  'DTG4',
  'DU15',
  'DTG5',
  'ID22',
  'NE11',
  'WHE3',
  'AVA1',
  'BL11',
  'HF11',
  'CS55',
  'LED7',
  'THT1',
  'RSF1',
  'AT66',
  'OT22',
  'CXT1',
  'BAB1',
  'JR55',
  'DU11',
  'NT01',
  'DEL0',
  '3GEN',
  'RN01',
  'RN02',
  'RN03',
  'TCC2',
  'DU14',
  'AV11',
  'SL33',
  'VV11',
  'TT22',
  'PX11',
  'CT22',
  'UE55',
  'USA2',
  'LED1',
  'GE10',
  'GF12',
  'GG11',
  'BT12',
  'LED5',
  'GE12',
  'HB13',
  'NF11',
  'JTS1',
  'GTI1',
  'TT11',
  'CT11',
  'IT55',
  'ET11',
  'AK13',
  'NL11',
  'NSL1',
  'BR11',
  'GLT1',
  'LINN',
  'NST1',
  'TCE1',
  'ST11',
  'WHE1',
  'TCC3',
  'HF55',
  'GX11',
  'RL23',
  'HF01',
  'SGY1',
  'BH11',
  'AS11',
  'RO01',
  'RO02',
  'RO03',
  'DE22',
  'YAT1',
  'RP01',
  'RP02',
  'RP03',
  'SN01',
  'SN02',
  'SN03',
  'PP11',
  'FLY3',
  'FLY2',
  'FLY1',
  'SC01',
  'SC02',
  'SC03',
  'BRR1',
  'TSF1',
  'SK03',
  'EXC1',
  'ZBE1',
  'ELF1',
  'HK11',
  'IGT1',
  'DMK1',
  'UND1',
  'ARB1',
  'FAL1',
  'SF02',
  'SF03',
  'FT11',
  'VHL1',
  'ZBE2',
  'PJT1',
  'SG01',
  'SG02',
  'SG03',
  'CC11',
  'BES1',
  'SDA1',
  'CBT2',
  'CZ01',
  'L701',
  'ML17',
  'ML30',
  'RAW5',
  'IV11',
  'RD02',
  'ML40',
  'ML31',
  'RD01',
  'RAW4',
  'LF02',
  'ML04',
  'ML14',
  'ML08',
  'ME33',
  'RAW9',
  'CZ02',
  'ARI3',
  'CZ05',
  'WL02',
  'GAM1',
  'DTM1',
  'USA1',
  'RD03',
  'SL09',
  'RAW7',
  'LF01',
  'CZ06',
  'RAW0',
  'ARC1',
  'ATL1',
  'RAW2',
  'KMB1',
  'KSP1',
  'CU01',
  'CZ03',
  'BHU1',
  'SL21',
  'ML10',
  'KMB2',
  'RAW8',
  'MLT1',
  'MLT2',
  'MLT3',
  'MLT4',
  'MA02',
  'JUG1',
  'NEW2',
  'RAW1',
  'CBT1',
  'RS11',
  'HAL1',
  'MET1',
  'ML09',
  'USC3',
  'USC2',
  'SLR1',
  'ML06',
  'RAW3',
  'ML32',
  'SL13',
  'HTS1',
  'WOR2',
  'WO01',
  'NAT1',
  'FUG1',
  'HS11',
  'CWK8',
  'WA11',
  'HIC1',
  'CWK3',
  'CWK2',
  'CWK1',
  'RR03',
  'CWK5',
  'HRT1',
  'CAR1',
  'SAF2',
  'NW11',
  'SAF1',
  'LP11',
  'ZT11',
  'ZHA1',
  'MA12',
  'HUM3',
  'AT11',
  'CWK7',
  'MEL1',
  'HUM1',
  'GFS2',
  'ZIY2',
  'HH22',
  'FR11',
  'AKA1',
  'GFS1',
  'RIP1',
  'MA77',
  'HIC2',
  'STL0',
  'CWK6',
  'DB11',
  'GA22',
  'CWK4',
  'ACE1',
  'WT24',
  'WT14',
  'WIT6',
  'WT32',
  'NA83',
  'WIT9',
  'XFR6',
  'BTLRSXF',
  'XFR1',
  'WT31',
  'WT27',
  'WT35',
  'GST2',
  'CKH1',
  'WIT5',
  'WIT7',
  'WT33',
  'WIT4',
  'WIT3',
  'WIT8',
  'DTR1',
  'CKH2',
  'DE33',
  'WXP2',
  'XFR7',
  'XFR8',
  'WC11',
  'GST1',
  'WIT2',
  'JD11',
  'JMB1',
  'DXP1',
  'WIT1',
  'XFR5',
  'UG33',
  'WXP1',
  'WT30',
  'WT22',
  'MCH1',
  'XFR2',
  'CHH1',
  'WTT0',
  'WT26',
  'HAM1',
  'EA22',
  'WT28',
  'WT23',
  'XFR4',
  'WT11',
  'SX01',
  'SX02',
  'SX03',
  'SX04',
  'SX05',
  'SX06',
  'SX07',
  'SX08',
  'SX09',
  'WT15',
  'LB11',
  'WIT0',
  'WT13',
  'WT36',
  'WT25',
  'XFRX',
  'TU01',
  'TU02',
  'TU03',
  'FB11',
  'IND1',
  'ID11',
  'TRT5',
  'TRT6',
  'OTM1',
  'MFF2',
  'TRT7',
  'PL13',
  'ASA1',
  'PID1',
  'TOL1',
  'MED2',
  'TRT0',
  'TL11',
  'ASA2',
  'PL12',
  'NAR1',
  'TRT3',
  'OR11',
  'JSM1',
  'KE22',
  'TRT8',
  'MWI1',
  'MWR1',
  'TRS4',
  'NOV1',
  'TRT1',
  'BIS1',
  'MED1',
  'MED3',
  'LON1',
  'WIC4',
  'WIC3',
  'STS4',
  'CT88',
  'TRT4',
  'IT11',
  'NA69',
  'WIC6',
  'MUN1',
  'SEF1',
  'GA11',
  'IT12',
  'TRT2',
  'TRT9',
  'LIB1',
  'TWS1',
  'MFF1',
  'NOV2',
  'PL11',
  'MWF1',
  'WIC5',
  'WI01',
  'WI02',
  'WI03',
  'NOV3',
  'JEB1',
  'WT01',
  'WT02',
  'WT03'
);

-- Update locationId based on homeTerminalCode
UPDATE carrier_drivers cd
SET "locationId" = l.id
FROM locations l
WHERE l.code = cd."homeTerminalCode"
AND cd."homeTerminalCode" IS NOT NULL;
